import Link from "next/link";
const services=[["✈","Flights","Find your way to the Caribbean"],["⇄","Island Hopping","Move between islands"],["🚙","Airport Transfers","Arrive in comfort"],["◉","Get a Ride","Move like a local"],["☀","Experiences","Book unforgettable days"],["⌁","Beaches","Find your perfect coast"],["♬","Nightlife","After-dark island energy"],["✦","Food","Taste the Caribbean"],["◇","Rentals","Cars, bikes & more"]];
const islands=["Jamaica","Barbados","St. Lucia","Bahamas","Cayman","Antigua"];
const trips=[["North Coast Escape","Montego Bay → Negril","3 days","From $389"],["South Coast Unfiltered","Kingston → Treasure Beach","4 days","From $529"],["Blue Mountains & City","Kingston → Blue Mountains","2 days","From $279"]];
export default function Home(){return <main>
<header><Link className="brand" href="/"><span>ISL</span><b>O</b><span>RA</span></Link><nav><Link href="/explore">Explore</Link><Link href="/flights">Flights</Link><Link href="/island-hopping">Island Hop</Link><Link href="/roadtrips">Roadtrips</Link></nav><Link className="pill dark" href="/trips">My Trips</Link></header>
<section className="hero"><div className="eyebrow">THE CARIBBEAN, CONNECTED</div><h1>Experience<br/><em>every island.</em></h1><p>Flights, island hopping, rides and unforgettable experiences — planned in one beautiful place.</p>
<div className="search"><div className="tabs"><Link href="/flights">✈ Flights</Link><Link href="/island-hopping">⇄ Island Hopping</Link><Link href="/explore">⌖ Explore an Island</Link></div><div className="fields"><label>FROM<strong>Miami (MIA)</strong></label><span>→</span><label>TO<strong>Kingston (KIN)</strong></label><label>WHEN<strong>Oct 18 — Oct 25</strong></label><Link className="go" href="/explore">Explore →</Link></div></div>
<div className="scroll">SCROLL TO DISCOVER ↓</div></section>
<section id="explore" className="section"><div className="sectionHead"><div><small>EVERYTHING YOU NEED</small><h2>Your island, your way.</h2></div><p>From touchdown to sunset, ISLORA puts the whole Caribbean experience in your hand.</p></div><div className="services">{services.map((s,i)=><article key={s[1]} className={i===0?"featured":""}><i>{s[0]}</i><h3>{s[1]}</h3><p>{s[2]}</p><span>→</span></article>)}</div></section>
<section id="roadtrip" className="road"><div className="roadcopy"><small>ISLORA SIGNATURE</small><h2>Caribbean<br/><em>Roadtrip.</em></h2><p>Go beyond the resort. Curated routes, local stops and the freedom to discover Jamaica at your own pace.</p><Link className="pill light" href="/roadtrips">Build my roadtrip →</Link></div><div className="triplist">{trips.map((t,i)=><article key={t[0]}><span>0{i+1}</span><div><h3>{t[0]}</h3><p>{t[1]} · {t[2]}</p></div><strong>{t[3]}</strong></article>)}</div></section>
<section id="islands" className="section islands"><small>START SOMEWHERE BEAUTIFUL</small><h2>Pick an island.</h2><div className="islandgrid">{islands.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>{i===0?"Now exploring":"Coming into focus"}</p></article>)}</div></section>
<section className="cta"><small>YOUR NEXT STORY STARTS HERE</small><h2>More island.<br/><em>Less ordinary.</em></h2><Link className="pill light" href="/explore">Explore Jamaica →</Link></section>
<footer><Link className="brand" href="/"><span>ISL</span><b>O</b><span>RA</span></Link><p>Experience Every Island.</p><p>Jamaica · Caribbean · 2026</p></footer>
</main>}